### ISSUE TITLE
Upgrade to 2021.7

### ISSUE THREAD

**Issue by JDStudiosAuto** [andyalm/homeassistant-scout-alarm#13] opened 2021-07-12 02:20 UTC
After the upgrade to 2021.7 my Scout integration broke. There is no indication why the integration just shows disabled entitiies.

**Comment by andyalm** [comment] 2021-07-12 17:21
I just upgraded today and reproduced the problem. I was able to trace the problem to a change in the `websocket-client` library, which is a dependency of this integration. I have pushed a fix to `master` (876bab2a206870e103145259e7f800950546e1ce). It resolved the issue for me. Let me know if it works for you.

**Comment by JDStudiosAuto** [comment] 2021-07-13 04:50
I removed the custom components and reinstalled. That itself did not work. After I reinstalled I still had to copy the new manifest file into the custom components directory. Which then worked after restart. Everything recongnized and working well.

Thank you.

From: Andy Alm ***@***.***>
Date: Monday, July 12, 2021 at 1:21 PM
To: andyalm/homeassistant-scout-alarm ***@***.***>
Cc: JDStudiosAuto ***@***.***>, Author ***@***.***>
Subject: Re: [andyalm/homeassistant-scout-alarm] Upgrade to 2021.7 (#13)

I just upgraded today and reproduced the problem. I was able to trace the problem to a change in the websocket-client library, which is a dependency of this integration. I have pushed a fix to master (876bab2<https://github.com/andyalm/homeassistant-scout-alarm/commit/876bab2a206870e103145259e7f800950546e1ce>). It resolved the issue for me. Let me know if it works for you.

**Comment by JDStudiosAuto** [comment] 2021-07-13 04:52
I removed the custom components and reinstalled. That itself did not work. After I reinstalled I still had to copy the new manifest file into the custom components directory. Which then worked after restart. Everything recongnized and working well.
 
Thank you.

**Comment by andyalm** [comment] 2021-07-17 18:47
Closing since the issue appears to be resolved now.

**Closed as completed by andyalm** 2021-07-17 18:47 UTC
